Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/03/2023
Var
// Seção de Declarações das variáveis 
c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para c<-1 ate 50 faca
  escreva (c)
fimpara
Fimalgoritmo